export const voiceList = [
  {
    label: 'Miền Nam',
    value: 'Miền Nam',
  },
  {
    label: 'Miền Trung',
    value: 'Miền Trung',
  },
  {
    label: 'Miền Bắc',
    value: 'Miền Bắc',
  },
]

export const classLevelList = [
  {
    label: 'Lớp 10',
    value: 10,
  },
  {
    label: 'Lớp 11',
    value: 11,
  },
  {
    label: 'Lớp 12',
    value: 12,
  },
]

export const genderList = [
  {
    value: 'MALE',
    label: 'Nam',
  },
  {
    value: 'FEMALE',
    label: 'Nữ',
  },
  {
    value: 'OTHER',
    label: 'Khác',
  },
]

export const cityList = [
  {
    name: 'An Giang',
    value: 'an-giang',
    type: 'tinh',
    label: 'Tỉnh An Giang',
    code: '89',
  },
  {
    name: 'Kon Tum',
    value: 'kon-tum',
    type: 'tinh',
    label: 'Tỉnh Kon Tum',
    code: '62',
  },
  {
    name: 'Đắk Nông',
    value: 'dak-nong',
    type: 'tinh',
    label: 'Tỉnh Đắk Nông',
    code: '67',
  },
  {
    name: 'Sóc Trăng',
    value: 'soc-trang',
    type: 'tinh',
    label: 'Tỉnh Sóc Trăng',
    code: '94',
  },
  {
    name: 'Bình Phước',
    value: 'binh-phuoc',
    type: 'tinh',
    label: 'Tỉnh Bình Phước',
    code: '70',
  },
  {
    name: 'Hưng Yên',
    value: 'hung-yen',
    type: 'tinh',
    label: 'Tỉnh Hưng Yên',
    code: '33',
  },
  {
    name: 'Thanh Hóa',
    value: 'thanh-hoa',
    type: 'tinh',
    label: 'Tỉnh Thanh Hóa',
    code: '38',
  },
  {
    name: 'Quảng Trị',
    value: 'quang-tri',
    type: 'tinh',
    label: 'Tỉnh Quảng Trị',
    code: '45',
  },
  {
    name: 'Tuyên Quang',
    value: 'tuyen-quang',
    type: 'tinh',
    label: 'Tỉnh Tuyên Quang',
    code: '08',
  },
  {
    name: 'Quảng Ngãi',
    value: 'quang-ngai',
    type: 'tinh',
    label: 'Tỉnh Quảng Ngãi',
    code: '51',
  },
  {
    name: 'Hà Nội',
    value: 'ha-noi',
    type: 'thanh-pho',
    label: 'Thành phố Hà Nội',
    code: '01',
  },
  {
    name: 'Lào Cai',
    value: 'lao-cai',
    type: 'tinh',
    label: 'Tỉnh Lào Cai',
    code: '10',
  },
  {
    name: 'Vĩnh Long',
    value: 'vinh-long',
    type: 'tinh',
    label: 'Tỉnh Vĩnh Long',
    code: '86',
  },
  {
    name: 'Lâm Đồng',
    value: 'lam-dong',
    type: 'tinh',
    label: 'Tỉnh Lâm Đồng',
    code: '68',
  },
  {
    name: 'Bình Định',
    value: 'binh-dinh',
    type: 'tinh',
    label: 'Tỉnh Bình Định',
    code: '52',
  },
  {
    name: 'Nghệ An',
    value: 'nghe-an',
    type: 'tinh',
    label: 'Tỉnh Nghệ An',
    code: '40',
  },
  {
    name: 'Kiên Giang',
    value: 'kien-giang',
    type: 'tinh',
    label: 'Tỉnh Kiên Giang',
    code: '91',
  },
  {
    name: 'Hà Giang',
    value: 'ha-giang',
    type: 'tinh',
    label: 'Tỉnh Hà Giang',
    code: '02',
  },
  {
    name: 'Phú Yên',
    value: 'phu-yen',
    type: 'tinh',
    label: 'Tỉnh Phú Yên',
    code: '54',
  },
  {
    name: 'Lạng Sơn',
    value: 'lang-son',
    type: 'tinh',
    label: 'Tỉnh Lạng Sơn',
    code: '20',
  },
  {
    name: 'Đà Nẵng',
    value: 'da-nang',
    type: 'thanh-pho',
    label: 'Thành phố Đà Nẵng',
    code: '48',
  },
  {
    name: 'Sơn La',
    value: 'son-la',
    type: 'tinh',
    label: 'Tỉnh Sơn La',
    code: '14',
  },
  {
    name: 'Tây Ninh',
    value: 'tay-ninh',
    type: 'tinh',
    label: 'Tỉnh Tây Ninh',
    code: '72',
  },
  {
    name: 'Nam Định',
    value: 'nam-dinh',
    type: 'tinh',
    label: 'Tỉnh Nam Định',
    code: '36',
  },
  {
    name: 'Lai Châu',
    value: 'lai-chau',
    type: 'tinh',
    label: 'Tỉnh Lai Châu',
    code: '12',
  },
  {
    name: 'Bến Tre',
    value: 'ben-tre',
    type: 'tinh',
    label: 'Tỉnh Bến Tre',
    code: '83',
  },
  {
    name: 'Khánh Hòa',
    value: 'khanh-hoa',
    type: 'tinh',
    label: 'Tỉnh Khánh Hòa',
    code: '56',
  },
  {
    name: 'Bình Thuận',
    value: 'binh-thuan',
    type: 'tinh',
    label: 'Tỉnh Bình Thuận',
    code: '60',
  },
  {
    name: 'Cao Bằng',
    value: 'cao-bang',
    type: 'tinh',
    label: 'Tỉnh Cao Bằng',
    code: '04',
  },
  {
    name: 'Hải Phòng',
    value: 'hai-phong',
    type: 'thanh-pho',
    label: 'Thành phố Hải Phòng',
    code: '31',
  },
  {
    name: 'Ninh Bình',
    value: 'ninh-binh',
    type: 'tinh',
    label: 'Tỉnh Ninh Bình',
    code: '37',
  },
  {
    name: 'Yên Bái',
    value: 'yen-bai',
    type: 'tinh',
    label: 'Tỉnh Yên Bái',
    code: '15',
  },
  {
    name: 'Gia Lai',
    value: 'gia-lai',
    type: 'tinh',
    label: 'Tỉnh Gia Lai',
    code: '64',
  },
  {
    name: 'Hoà Bình',
    value: 'hoa-binh',
    type: 'tinh',
    label: 'Tỉnh Hoà Bình',
    code: '17',
  },
  {
    name: 'Bà Rịa - Vũng Tàu',
    value: 'ba-ria-vung-tau',
    type: 'tinh',
    label: 'Tỉnh Bà Rịa - Vũng Tàu',
    code: '77',
  },
  {
    name: 'Cà Mau',
    value: 'ca-mau',
    type: 'tinh',
    label: 'Tỉnh Cà Mau',
    code: '96',
  },
  {
    name: 'Bình Dương',
    value: 'binh-duong',
    type: 'tinh',
    label: 'Tỉnh Bình Dương',
    code: '74',
  },
  {
    name: 'Cần Thơ',
    value: 'can-tho',
    type: 'thanh-pho',
    label: 'Thành phố Cần Thơ',
    code: '92',
  },
  {
    name: 'Thừa Thiên Huế',
    value: 'thua-thien-hue',
    type: 'tinh',
    label: 'Tỉnh Thừa Thiên Huế',
    code: '46',
  },
  {
    name: 'Đồng Nai',
    value: 'dong-nai',
    type: 'tinh',
    label: 'Tỉnh Đồng Nai',
    code: '75',
  },
  {
    name: 'Tiền Giang',
    value: 'tien-giang',
    type: 'tinh',
    label: 'Tỉnh Tiền Giang',
    code: '82',
  },
  {
    name: 'Điện Biên',
    value: 'dien-bien',
    type: 'tinh',
    label: 'Tỉnh Điện Biên',
    code: '11',
  },
  {
    name: 'Vĩnh Phúc',
    value: 'vinh-phuc',
    type: 'tinh',
    label: 'Tỉnh Vĩnh Phúc',
    code: '26',
  },
  {
    name: 'Quảng Nam',
    value: 'quang-nam',
    type: 'tinh',
    label: 'Tỉnh Quảng Nam',
    code: '49',
  },
  {
    name: 'Đắk Lắk',
    value: 'dak-lak',
    type: 'tinh',
    label: 'Tỉnh Đắk Lắk',
    code: '66',
  },
  {
    name: 'Thái Nguyên',
    value: 'thai-nguyen',
    type: 'tinh',
    label: 'Tỉnh Thái Nguyên',
    code: '19',
  },
  {
    name: 'Hải Dương',
    value: 'hai-duong',
    type: 'tinh',
    label: 'Tỉnh Hải Dương',
    code: '30',
  },
  {
    name: 'Bạc Liêu',
    value: 'bac-lieu',
    type: 'tinh',
    label: 'Tỉnh Bạc Liêu',
    code: '95',
  },
  {
    name: 'Trà Vinh',
    value: 'tra-vinh',
    type: 'tinh',
    label: 'Tỉnh Trà Vinh',
    code: '84',
  },
  {
    name: 'Thái Bình',
    value: 'thai-binh',
    type: 'tinh',
    label: 'Tỉnh Thái Bình',
    code: '34',
  },
  {
    name: 'Hà Tĩnh',
    value: 'ha-tinh',
    type: 'tinh',
    label: 'Tỉnh Hà Tĩnh',
    code: '42',
  },
  {
    name: 'Ninh Thuận',
    value: 'ninh-thuan',
    type: 'tinh',
    label: 'Tỉnh Ninh Thuận',
    code: '58',
  },
  {
    name: 'Đồng Tháp',
    value: 'dong-thap',
    type: 'tinh',
    label: 'Tỉnh Đồng Tháp',
    code: '87',
  },
  {
    name: 'Long An',
    value: 'long-an',
    type: 'tinh',
    label: 'Tỉnh Long An',
    code: '80',
  },
  {
    name: 'Hậu Giang',
    value: 'hau-giang',
    type: 'tinh',
    label: 'Tỉnh Hậu Giang',
    code: '93',
  },
  {
    name: 'Quảng Ninh',
    value: 'quang-ninh',
    type: 'tinh',
    label: 'Tỉnh Quảng Ninh',
    code: '22',
  },
  {
    name: 'Phú Thọ',
    value: 'phu-tho',
    type: 'tinh',
    label: 'Tỉnh Phú Thọ',
    code: '25',
  },
  {
    name: 'Quảng Bình',
    value: 'quang-binh',
    type: 'tinh',
    label: 'Tỉnh Quảng Bình',
    code: '44',
  },
  {
    name: 'Hồ Chí Minh',
    value: 'ho-chi-minh',
    type: 'thanh-pho',
    label: 'Thành phố Hồ Chí Minh',
    code: '79',
  },
  {
    name: 'Hà Nam',
    value: 'ha-nam',
    type: 'tinh',
    label: 'Tỉnh Hà Nam',
    code: '35',
  },
  {
    name: 'Bắc Ninh',
    value: 'bac-ninh',
    type: 'tinh',
    label: 'Tỉnh Bắc Ninh',
    code: '27',
  },
  {
    name: 'Bắc Giang',
    value: 'bac-giang',
    type: 'tinh',
    label: 'Tỉnh Bắc Giang',
    code: '24',
  },
  {
    name: 'Bắc Kạn',
    value: 'bac-kan',
    type: 'tinh',
    label: 'Tỉnh Bắc Kạn',
    code: '06',
  },
]
